global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: kafka
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: spark-master
    metrics_path: /metrics/executors
    static_configs:
      - targets: ['spark-master:4040']

  - job_name: flink
    metrics_path: /jobmanager/metrics
    params:
      get:
        - true
    static_configs:
      - targets: ['flink-jobmanager:8081']

  - job_name: generator
    static_configs:
      - targets: ['generator:8000']

  - job_name: probe
    static_configs:
      - targets: ['probe:8001']
