---
- name: "Fase 1/6 — Configuración base nodos principales"
  hosts: producers:broker:sink
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ hostvars[groups['compute_brazil'][0]].inventory_hostname }}"
  roles:
    - common

- name: "Fase 2/6 — Configuración base compute Brasil"
  hosts: compute_brazil
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ inventory_hostname }}"
    vm_broker_ip: "{{ hostvars[groups['broker'][0]].inventory_hostname }}"
    vm_sink_ip: "{{ hostvars[groups['sink'][0]].inventory_hostname }}"
  roles:
    - common

- name: "Fase 3/6 — Levantar Message Broker principal"
  hosts: broker
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ hostvars[groups['compute_brazil'][0]].inventory_hostname }}"
  roles:
    - broker

- name: "Fase 4/6 — Levantar Persistencia principal"
  hosts: sink
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ hostvars[groups['compute_brazil'][0]].inventory_hostname }}"
  roles:
    - sink

- name: "Fase 5/6 — Levantar Compute en Brasil"
  hosts: compute_brazil
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ inventory_hostname }}"
    vm_broker_ip: "{{ hostvars[groups['broker'][0]].inventory_hostname }}"
    vm_sink_ip: "{{ hostvars[groups['sink'][0]].inventory_hostname }}"
  roles:
    - compute

- name: "Fase 6/6 — Preparar Producer principal"
  hosts: producers
  become: yes
  gather_facts: yes
  vars:
    vm_compute_ip: "{{ hostvars[groups['compute_brazil'][0]].inventory_hostname }}"
  roles:
    - producer
