plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow'
}

dependencies {
    implementation project(':common')
    implementation "org.apache.flink:flink-java:${flinkVersion}"
    implementation "org.apache.flink:flink-streaming-java:${flinkVersion}"
    implementation "org.apache.flink:flink-clients:${flinkVersion}"
    implementation "org.apache.flink:flink-connector-kafka:${flinkConnectorVersion}"
    implementation "org.apache.flink:flink-connector-jdbc:${flinkConnectorVersion}"
    implementation "org.postgresql:postgresql:${postgresVersion}"
}

shadowJar {
    archiveFileName = 'streaming-job.jar'
    mergeServiceFiles()
    zip64 true
}
