plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow'
}

dependencies {
    implementation project(':common')
    compileOnly "org.apache.spark:spark-core_${scalaBinaryVersion}:${sparkVersion}"
    compileOnly "org.apache.spark:spark-sql_${scalaBinaryVersion}:${sparkVersion}"
    compileOnly "org.apache.spark:spark-streaming_${scalaBinaryVersion}:${sparkVersion}"
    implementation "org.postgresql:postgresql:${postgresVersion}"
}

shadowJar {
    archiveFileName = 'microbatch-job.jar'
}
